### PR TITLE
Change caution style in trial-ride page

### PR DESCRIPTION
**Pull request by jmblog**

### CODE REVIEW

**Comment by jmblog** [comment]
@bokkura-rex What do you think about this change?

image

**Comment by bokkura-rex** [comment]
Cool, you added the disclaimer and "about"-page, and changed the style of the trial ride caution.
Yes, better to not highlight in red I think. However using a 'slightly' smaller font sometimes is problematic design-wise I think: It looks unintended (looks like the font is a little different by mistake, not intentionally). I have that sometimes when I draft something at my work. If using different font sizes, is usually better to choose a font size that is more clearly different. In our case however again, making the text even smaller will probably look bad, so I am not sure what to suggest. Maybe adding a header like the "試乗会の基本的条件" may help. I'd say we try this, first with the caution text in the smaller font as it is now, and if this looks not good, simply change the font size back to normal.
BTW, I think the 2 paragraphs above (starting from "ご用意できる ...") the small-font size text can go under that header and become smaller font too. It is late night now, I will try it out myself on day time.

Thanks for the other two pages! I will think about how to improve the "About" text. Generally I think the story should be shorter, the 理念 more straight-forward/simple. Will think about it this weekend.
For the disclaimer page, should we add saying that we will not give any customer data to anybody else except where required by law ?

**Comment by jmblog** [comment]
### trial ride caution

> Maybe adding a header like the "試乗会の基本的条件" may help.

Right, that's better. I've added the header "試乗会に関する注意事項" and change the font size back to normal. What do you think about it?
https://github.com/bokkura-expedition/bokkura.com/commit/6764b11d9782d18f9f79588be15cb3feea56d332

### disclaimer page

I've also updated the privacy policies text by referring other website's privacy policies.

Among these policies, "第三者のサイバー攻撃による障害に対する責任を負いません。" might be changed I think. A user might have the impression that we lack the responsibility.

This text might be changed to like "当社は、個人情報の正確性及び最新性を保ち、安全に管理するとともに個人情報の紛失、改ざん、漏えいなどを防止するため、必要かつ適正な情報セキュリティ対策を実現します。".

**Comment by bokkura-rex** [comment]
**trial ride caution:**
Yes, very nice !

**disclaimer page**
Yep, I totally agree, being too expressiv about not assuming responsibility may also scare people a bit, and as you say wonder if we are safe enough anyway. Just a simple hint, and a simple robust statement that we don't share customer info with anybody else (except Klepper when registering a customer's boat for warranty), and do everything we think is necessary to be on a very safe side with customer data we have received.
Now only a comment, will have to see when I can edit a bit more today or tonight ...

**Pull request merged**
